선택 페이지 컴포넌트, 단위 테스트
minjeongHEO/Job-Cracker pull request #18
Opened 2024-12-30 14:59 UTC by minjeongHEO

## #️⃣연관된 이슈

> Closes #15 - 테스팅 설정
> Closes #11 - SelectButton 컴포넌트 테스트
> Closes #16 - TopicSelector 컴포넌트 테스트
> Closes #17 - TopicSelector 커스텀훅 단위 테스트

## 📝작업 내용

> 테스트 환경 설정, 컴포넌트 테스트, 단위 테스트
### 1. 테스트 환경 설정
- Vitest, Testing Library 설정
- Jest DOM matcher 설정

### 2. 컴포넌트 테스트
#### SelectButton 컴포넌트
- 렌더링 테스트
- 선택 상태 테스트
- 클릭 이벤트 테스트

#### TopicSelector 컴포넌트
- 렌더링 테스트
- 주제 선택/해제 동작 테스트
- 전체 선택 동작 테스트
- 라우팅 테스트

### 3. 커스텀 훅 단위 테스트
- useTopicSelector 훅 테스트
- 주제 선택/해제 로직 테스트
- 전체 선택/해제 로직 테스트
- 선택 상태 확인 로직 테스트

### 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/c6c9afa6-ac56-4fa6-9b1c-12cdd57cb18b)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-12-30 16:01 UTC, schnee98 requested changes
테스트 시도 좋네용 특히 저도 `renderHook` 으로 훅을 테스트 하는 방법도 있다는걸 이번에 리뷰 하면서 알게 되었어요!

2024-12-30 16:01 UTC, schnee98 commented on app/_components/TopicSelector.test.tsx
> +        `/interview/select/${defaultProps.devType}/prepare?topics=${firstTopicName}`
여기는 `ROUTES.TOPIC.build()` 를 사용할 수 없었나요?

2024-12-30 16:01 UTC, schnee98 commented on app/_hooks/useTopicSelector.ts
> +  };
둘다 이벤트 핸들러인 것 같은데, 네이밍 컨벤션이 통일되지 않은 느낌이네요

2024-12-30 16:01 UTC, schnee98 commented on app/_hooks/useTopicSelector.ts
> +    isSelectedTopic,
매우 사소하지만, isAllSelected와 isSelectedTopic이 흩어져 있어서 정리가 되어있지 않은 느낌이 들어요

2024-12-30 16:01 UTC, schnee98 commented on app/_components/SelectButton.tsx
> +      className={clsx(styles.wrapper, { [styles['wrapper--selected']]: isSelected })}
이런 클래스는 함수로 분리해보아도 좋을 것 같네용

```typescript
function wrapperClass(selected: boolean) {
  return clsx(styles.wrapper, {
    [styles['wrapper--selected']]: selected,
  });
}
```

2024-12-30 16:01 UTC, schnee98 commented on app/_components/TopicSelector.test.tsx
> +const firstTopicName = defaultProps.topics[0];
```suggestion
const [firstTopicName] = defaultProps.topics;
```

2024-12-31 05:06 UTC, minjeongHEO commented on app/_components/TopicSelector.test.tsx
> +        `/interview/select/${defaultProps.devType}/prepare?topics=${firstTopicName}`
완전 가능해요 ㅎㅎㅎㅎㅎ 급하게 올리느라 놓쳣어요! 반영할게요~!

2024-12-31 05:07 UTC, minjeongHEO commented on app/_components/SelectButton.tsx
> +      className={clsx(styles.wrapper, { [styles['wrapper--selected']]: isSelected })}
헉

2024-12-31 05:18 UTC, minjeongHEO commented on app/_components/TopicSelector.test.tsx
> +const firstTopicName = defaultProps.topics[0];
오!

2024-12-31 05:39 UTC, minjeongHEO commented on app/_hooks/useTopicSelector.ts
> +    isSelectedTopic,
저도 약간 비슷한 느낌을 받았어요 ㅋㅋㅋㅋㅋㅋ

2024-12-31 07:58 UTC, schnee98 approved these changes

2024-12-31 07:58 UTC, schnee98 commented on app/_components/TopicSelector.tsx
> +      <button className={styles['next-button']} onClick={navigateToNext} disabled={notSelected}>
요거는 clsx 쓰는 부분을 리팩토링 하는 과정에서 발견하였는데요. 버튼에는 `disabled`라는 속성이 있어요.
`--visible`이라는 클래스를 더 만들고 `clsx`에서 상태를 구분하기보다 `next-button` 클래스에 disabled 여부에 따라 css 안에서 스타일을 다르게 적용하는 방법을 적용하였습니다.
이렇게 하면 css만으로 스타일 속성 적용을 바꿀 수 있으니 자바스크립트 연산을 조금이라도 더 줄일 수 있을 것 같아요~

2024-12-31 07:59 UTC, schnee98 commented on app/_components/TopicSelector.module.scss
> +  opacity: 0;
이거는 css에서 `next-button` 클래스만으로 스타일을 적용하는 방식입니당

2024-12-31 08:15 UTC, minjeongHEO commented on app/_components/TopicSelector.tsx
> +      <button className={styles['next-button']} onClick={navigateToNext} disabled={notSelected}>
우와 맞네요!! 짱이당

2024-12-31 08:17 UTC, minjeongHEO commented on app/_components/TopicSelector.module.scss
> +  opacity: 0;
훨 씬 좋 아 요 😦

2024-12-31 08:18 UTC, merged