질문/답변 페이지로 넘어가기 전 클라이언트 상태 관리 도입
minjeongHEO/Job-Cracker pull request #24
Opened 2024-12-31 14:21 UTC by minjeongHEO

## #️⃣연관된 이슈

> #3 
> Closes #19 - 선택한 주제 클라이언트 상태 관리

## 📝작업 내용

> 클라이언트 상태관리 도입 (Zustand)

### 문제 상황
- 기존에는 선택한 주제를 URL 쿼리 파라미터로 관리
- 구현 하려는 페이지는 SPA가 적합하다고 판단
- SPA 특성상 URL 조작 시 상태 유실 위험
- 면접 진행 중 상태 관리 필요성

### 해결 방법
1. Zustand 도입
   - 보일러플레이트가 적은 경량화된 상태관리 라이브러리 선택
   - 간단한 설정
   - React 18 및 Next.js 13 App Router와 호환성 우수

2. 스토어 설계
 ```typescript
   interface InterviewStore {
     devType: DeveloperType | null;
     select: {
       topics: string[];
       subTopics: string[];
     };
     // ... actions
   }
```
일단은 개발자타입, 주제, 서브 주제, 이렇게 저장하는 식으로 스토어를 구현해놨습니다.
추후 추가될 기능들은 기능을 구현하면서 고려해봐야겠습니다.

3. 상태 전환
- 선택 페이지에서 면접 페이지로 전환 시 상태 저장

2024-12-31 15:10 UTC, schnee98 requested changes
zustand를 도입하니 searchParams 및 라우팅으로 관리하던 개발자 타입, 토픽, 세부 토픽 상태들을 서버에서 한번, zustand에서 한번 중복 관리하는 느낌이 들어요.
어느 방식이든 하나로만 관리해야할 것 같아요.

2024-12-31 15:10 UTC, schnee98 commented on app/_components/TopicSelector.tsx
> +    updateSelect({ topics: previousTopics, subTopics: selectedTopics });
`devType`은 `SelectPage` 컴포넌트에서,
`topics`는 `handleTopicNavigation`에서,
`subTopics`는 `handleSubTopicNavigation`에서
업데이트를 하는게 더 자연스러워 보여용

2024-12-31 15:12 UTC, schnee98 commented
> React 18 및 Next.js 13 App Router와 호환성 우수
현재 프로젝트에 사용하고 계신 버전들은 React 19, Next.js 15로 보이는데 이 버전에도 호환성이 우수한가요?

2025-01-01 04:10 UTC, minjeongHEO commented
> zustand를 도입하니 searchParams 및 라우팅으로 관리하던 개발자 타입, 토픽, 세부 토픽 상태들을 서버에서 한번, zustand에서 한번 중복 관리하는 느낌이 들어요. 어느 방식이든 하나로만 관리해야할 것 같아요.

서버컴포넌트를 사용하고 싶은데,,,
포기해야할까요,,,?🥹

2025-01-01 06:11 UTC, schnee98 commented
> 서버컴포넌트를 사용하고 싶은데,,,
> 포기해야할까요,,,?🥹

서버컴포넌트를 사용하고 싶으면 zustand를 포기하면 되지요

2025-01-01 06:45 UTC, minjeongHEO commented
> > 서버컴포넌트를 사용하고 싶은데,,,
> > 포기해야할까요,,,?🥹
> 
> 서버컴포넌트를 사용하고 싶으면 zustand를 포기하면 되지요

저는 두 가지 상태 관리 방식을 단계적으로 사용하는게 좋은 접근이라고 생각해서
선택 페이지들 (SSR)
면접 페이지 (SPA)
이렇게 사용하고싶었거든요

그래서 처음에 슈니라 리뷰해준 것처럼
>devType은 SelectPage 컴포넌트에서, 
>topics는 handleTopicNavigation에서,
>subTopics는 handleSubTopicNavigation에서 업데이트를 하는게 더 자연스러워 보여용

에 리뷰에 동의를 했는데

또

상태 전환 시점(zustand)을 subTopic쪽에서 해주는게 흐름상 맞는거같기도하고..............................


어떻게 생각하시나요!!!? (약간의 설득)

2025-01-01 07:12 UTC, schnee98 commented
마지막 주제선택할 때 상태를 넘기는 것도 괜찮은 방법 중 하나인 것 같기는 한데요.
그렇게 한다면 결국 한 페이지 (질문 페이지) 에서만 상태를 받아 사용하는데, 외부 전역 상태 관리 라이브러리를 굳이 사용해야하나 싶기도 해요.

zustand를 사용하는데 의문이 드는 부분이 몇가지 있는데요.
1. 질문 페이지에서 사용하는 상태를 굳이 라이브러리를 사용해가면서 관리해야 하는지?
2. 서버 컴포넌트와 params, searchParams로 주제 선택을 할 때 예시로 사용자가 세부 주제 선택 페이지부터 사용을 시작하면 zustand에 상태를 질문 페이지에 제대로 전달이 가능한지?
3. 모든 페이지에서 클라이언트 컴포넌트를 주로 다룬다면 굳이 next가 필요할지?

위 부분들을 고민하면서 결정하시면 좋을 것 같네요

2025-01-02 06:56 UTC, merged